name: 'Beta Release (No Signing)'

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Triggers on push to 'main' branch
      - staging # Triggers on push to 'main' branch

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # macOS ARM (M1+)
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # macOS Intel
            args: '--target x86_64-apple-darwin'
          - platform: 'windows-latest' # Windows x64
            args: ''
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      # Install Linux dependencies
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libpipewire-0.3-dev libspa-0.2-dev pipewire

      # Setup Node.js
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm' # Change to 'yarn' or 'pnpm' if you use those

      # Setup Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # macOS targets
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.platform == 'windows-latest' && 'aarch64-pc-windows-msvc' || '' }}

      # Cache Rust dependencies
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # Install frontend dependencies
      - name: install frontend dependencies
        run: npm install # Change to 'yarn install' or 'pnpm install' if needed

      # Build and create release
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref == 'refs/heads/staging' && 'ominminds-v__VERSION__-pre' || 'omniminds-v__VERSION__' }} # Add -pre suffix for staging
          releaseName: ${{ github.ref == 'refs/heads/staging' && 'Omniminds Desktop v__VERSION__ (Pre-release)' || 'Omniminds Desktop v__VERSION__' }}
          releaseBody: 'Download Omniminds Desktop for your operating system below.'
          releaseDraft: false
          prerelease: ${{ github.ref == 'refs/heads/staging'}}
          includeRelease: true
          tauriScript: npm run tauri
          projectPath: '.'
          args: ${{ matrix.args }}